### ISSUE TITLE
Propagate AWS errors to users when deletion of connection fails

### ISSUE THREAD

**Issue by boaz-raz** [GlobalNOC/OESS#1243]
A user was working on trying to set up an Azure Cloud Connect circuit that ended up not working. He decided to delete what he was doing but when he clicked the little trash can he got the alert message. He did not click OK. The vlan listed in the error message, does appear to be related to what he was doing but this isn't the message he was expecting to see.

**Comment by jonstout** [comment]
When deleting a connection with an aws-hosted-connection endpoint, if an error occurs from the aws side we do not propagate the error to the user. Because attempts to delete aws hosted connections with associated virtual gateways will always fail, we must forward aws errors to the user (from what i recall the error message from aws is quite clear).
